### ISSUE TITLE
A question about Sickle

### ISSUE THREAD

**Issue by wushixian** [mloesch/sickle#2]
Dear Mr. Mathias.Loesch:
        I'm a researcher from Agriculture Information Institute, Chinese academy of agriculture sciences.
        I have used your sickle package for harvesting some data from a given OAI server, But the server need me to input the username and password, I sent the auth=("xxxxx","xxxx") into the sickle initialize sentence.
        Here's my code:
        sickle=Sickle('http://xxx.xxx.xx/xxx/oaihandler',auth=('xxx','xx'))
        records = sickle.ListRecords(metadataPrefix='oai_dc')

        but when I run the program, it told me like this:
        sickle.oaiexceptions.OAIError : username is required parameter for this verb.
        I searched the problem in internet for long time, but I didn't get the answer, So I finally decide to sent you the email.
        Sorry for bothering you for this.
        Thank you very much.
        My mail address is :cyunpeng@163.com.

Best Regards
Cui

**Comment by mloesch** [comment]
It looks like the OAI expects the username (and maybe also the password) as HTTP parameters. In this case, you could try the following:

```
sickle.ListRecords(metadataPrefix='oai_dc', username='xxx', password='xxx')
```

However, this is not standard OAI-PMH, so in case this does not work, you should talk to the maintainer of the OAI server about this problem.
