### ISSUE TITLE
`.encode` in `__repr__` incorrect

### ISSUE THREAD

**Issue by bronger** [mloesch/sickle#30]
I think the `encode` method calls in the `__repr__` methods on sickle/models.py is incorrect. FWIW, I get exceptions with those:

    >>> list(sickle.ListSets())
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.6/dist-packages/sickle/models.py", line 168, in __repr__
        return u'<Set %s>'.encode('utf8') % self.setName
    TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'

If I delete them, everything looks fine.

**Comment by mloesch** [comment]
Fixed in release 0.6.5
