### ISSUE TITLE
Connection broken: IncompleteRead

### ISSUE THREAD

**Issue by symac** [mloesch/sickle#33]
Hello,
when trying to harvest the data from the server ```http://staroai.theses.fr/OAIHandler``` with the ```tef``` metadataPrefix I end up getting a message saying : 

```Connection broken: IncompleteRead```

It's not easy to replicate as it happened, for my last two retries when trying to get page number 299 or page 155, so seems to be some king of timeout issue, but I am not sure on the best way to handle it.

**Comment by mloesch** [comment]
Cannot reproduce this. The only solution that I can think of is to call `record_iterator.next()` manually, catch the `IncompleteRead` Exception and implement a custom retry mechanism.
