### ISSUE TITLE
Retrieve selective fields for each record using ListRecords

### ISSUE THREAD

**Issue by saurabh-khanna** [mloesch/sickle#49]
Is it possible to retrieve selective fields for each record using ListRecords? For instance, I only want to get the publication date (and not description, authors. etc.) for each record.

**Comment by mloesch** [comment]
In case you really only need the publication date, you could have a look at the `ListIdentifiers` OAI method, it returns only the header information which also contains the date.

In case that should not be enough, you can also implement the record parsing yourself:
https://sickle.readthedocs.io/en/latest/customizing.html
