### ISSUE TITLE
Sickle retrieving partial data from collection

### ISSUE THREAD

**Issue by xialuoke4062** [mloesch/sickle#52]
Hi there,

I have been attempting to extract metadata from [this library](https://jscholarship.library.jhu.edu/handle/1774.2/34121) with this code: 
```
URL = 'https://jscholarship.library.jhu.edu/oai/request?set=col_1774.2_34121'
sickle = Sickle(URL)
records = sickle.ListRecords(metadataPrefix='oai_dc')
```

And it can return 6 out of 11 entries from this collection. I cannot figure out why the other 5 entries are missing. Any advice would be appreciated!

**Comment by mloesch** [comment]
How do you know there are 11 entries? The server only returns 6 records.

```
$ curl -s "https://jscholarship.library.jhu.edu/oai/request?set=col_1774.2_34121&verb=ListRecords&metadataPrefix=oai_dc" | grep "<record>" | wc -l
       6
```

 This is a question for the operator of the server, and not a problem of the library.

**Comment by xialuoke4062** [comment]
Thank you for the response. If you click on the library link (https://jscholarship.library.jhu.edu/handle/1774.2/34121), there are 11 papers under this collection. Am I doing anything wrong here? Really appreciate any advice.

**Comment by mloesch** [comment]
> Thank you for the response. If you click on the library link (https://jscholarship.library.jhu.edu/handle/1774.2/34121), there are 11 papers under this collection. Am I doing anything wrong here? Really appreciate any advice.

Please ask the operator of jscholarship.library.jhu.edu, problems with specific document servers are out of scope here.

**Comment by bmckinney** [comment]
I've just fixed some bugs in our OAI-PMH index. This should be resolved now.

`curl -s "https://jscholarship.library.jhu.edu/oai/request?set=col_1774.2_34121&verb=ListRecords&metadataPrefix=oai_dc" | grep "<record>" | wc -l
      11
`
